<?php
return [
	// Elfs
	'name-elf'			=>	'Elfos',
	'desc-elf'			=>	'Los elfos, de larga vida, son hijos del mundo natural, similares en muchas formas superficiales a las criaturas feéricas, pero también diferentes. Los elfos valoran su intimidad y sus tradiciones y, si bien a menudo son lentos en hacer amigos tanto a nivel personal como nacional, una vez un extraño es aceptado como camarada, tales alianzas pueden durar generaciones. Los elfos tienen un curioso apego a su entorno, quizá como resultado de su increíblemente larga vida, o quizá por razones más profundas y místicas. Los elfos que permanecen mucho tiempo en una región se adaptan físicamente para ajustarse a su entorno, y lo más notable de ello es que adoptan una coloración que refleja el entorno local. Los elfos que pasan sus vidas entre las razas de vida más corta, por otra parte, a menudo desarrollan una percepción malsana de la mortalidad, y se vuelven cínicos, resultado de contemplar envejecer y morir ante sus ojos a una oleada tras otra de compañeros.',
	'desc-physical-elf'	=>	'Aunque son generalmente más altos que los humanos, los elfos poseen un físico grácil y débil, acentuado por sus orejas largas y puntiagudas. Sus ojos son anchos y almendrados, provistos de pupilas grandes y de colores brillantes. Si bien su ropa a menudo refleja la belleza del mundo natural, los elfos que viven en las ciudades tienden a vestirse a la última moda.',
	'society-elf'		=>	'Muchos elfos están muy ligados a la Naturaleza, y tratan de vivir en armonía con el mundo natural. Sin embargo, la mayoría encuentra de mal gusto manipular la tierra y la piedra, y en su lugar prefieren cultivar artes más bellas, estando particularmente dotados para la magia debido a su innata paciencia.',
	'relation-elf'		=>	'Los elfos son dados a menospreciar a otras razas, tachándolas de precipitadas y de impulsivas, si bien son excelentes jueces del carácter. Un elfo podría no querer a un enano como vecino, pero sería el primero en reconocer su habilidad con la forja. Tienen a los gnomos por curiosidades extrañas (y a menudo, peligrosas), y por los medianos sienten cierta medida de piedad, puesto que a ojos de los elfos la Pequeña gente les parece que va a la deriva, sin un hogar tradicional. Los elfos están fascinados por los humanos, como evidencia el número de semielfos que hay en el mundo, incluso si suelen desheredar a tal progenie. Contemplan a los semiorcos con desconfianza y con sospecha.',
	'alignment-elf'		=>	'Los elfos son emocionales y caprichosos, pero aún así valoran la amabilidad y la belleza. La mayoría son caóticos buenos. Prefieren los dioses que comparten su amor por las cualidades místicas del mundo: Desna y Nethys son favoritos particulares entre ellos, la una por sus maravillas y su amor hacia los lugares salvajes, y el otro por su dominio de la magia. Calistria es quizá la más notoria de las diosas élficas, puesto que representa los ideales élficos llevados al extremo.',
	'adventure-elf'		=>	'Muchos elfos se embarcan en aventuras por un deseo de explorar el mundo, abandonando sus recluidos reinos boscosos para recuperar magia élfica olvidada, o buscar reinos perdidos que milenios atrás fundaran sus antepasados. Para los criados entre humanos, la vida efímera y libre de ataduras de un aventurero tiene un atractivo natural. Los elfos suelen desdeñar el combate cuerpo a cuerpo a causa de su fragilidad, prefiriendo en su lugar escoger clases como la de mago o la de explorador',
	'racial-elf'		=>	'<u>+2 a Destreza, +2 a Inteligencia, -2 a Constitución</u>: los elfos son ágiles, tanto de cuerpo como de mente, pero su forma es frágil.
	<br><u>Mediano</u>: los elfos son criaturas Medianas y no tienen bonificador ni penalizador debido al tamaño.
	<br><u>Velocidad normal</u>: los elfos tienen una velocidad base de 30 pies (9 m).
	<br><u>Visión en la penumbra</u>: los elfos pueden ver el doble que los humanos en condiciones de luz tenue.
	<br><u>Inmunidades élficas</u>: los elfos son inmunes a los efectos del sueño mágico, y obtienen un bonificador +2 racial a las tiradas de salvación contra los conjuros y efectos de hechizar.
	<br><u>Magia élfica</u>: los elfos obtienen un bonificador +2 racial a las pruebas de nivel de lanzador llevadas a cabo para superar la resistencia a los conjuros. Además, obtienen un bonificador +2 racial a las pruebas de Conocimiento de conjuros que tienen como objetivo identificar las propiedades de los objetos mágicos.
	<br><u>Sentidos agudos</u>: los elfos obtienen un bonificador +2 racial a las pruebas de Percepción.
	<br><u>Familiaridad con las armas</u>: los elfos son competentes con los arcos largos (incluyendo los arcos largos compuestos), las espadas largas, las espadas roperas, y los arcos cortos (incluyendo los arcos cortos compuestos), y tratan cualquier arma con la palabra ‘élfico’ en su nombre como un arma marcial. Idiomas: los elfos empiezan el juego hablando común y elfo. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger entre los siguientes: celestial, dracónico, goblin, gnoll, gnomo, orco, y silvano.',

	//Dwafs
	'name-dwaf'				=>	'Enanos',
	'desc-dwaf'				=>	'Los enanos son una raza estoica y adusta, atrincherada en ciudades excavadas en el corazón de las montañas, y ferozmente determinada a rechazar las depredaciones de razas salvajes como los orcos y los goblin. Más que cualquier otra raza, los enanos han adquirido la reputación de ser artesanos de la tierra, adustos y desprovistos de humor. Se podría decir que la historia enana da forma a la oscura disposición de muchos de ellos, puesto que residen en altas montañas y en peligrosos reinos bajo tierra, constantemente en guerra contra los gigantes, los goblin y otros horrores parecidos.',
	'desc-physical-dwaf'	=>	'Los enanos son una raza baja y robusta, y suelen medir 1 pie (30 cm) menos de altura que la mayoría de los humanos, con una masa corporal ancha y compacta, que justifica su recia apariencia. Tanto los enanos como las enanas se enorgullecen de la longitud de su cabello, por lo que los varones a menudo decoran su barba con una gran variedad de broches y trenzas intrincadas. Un enano totalmente afeitado es un signo seguro de locura… o peor. Nadie que esté familiarizado con la raza se fiaría de un enano sin barba.',
	'society-dwaf'			=>	'Las grandes distancias existentes entre sus ciudadelas de montaña explican muchas de las diferencias culturales que existen en la sociedad de los enanos. A pesar de estos cismas, todos los enanos del mundo se caracterizan por su amor por los trabajos en piedra, su pasión por la artesanía y la arquitectura basadas en piedra y metal, y por su odio feroz contra los gigantes, los orcos, y las diversas razas goblin.',
	'relation-dwaf'			=>	'Los enanos y los orcos llevan mucho tiempo viviendo cerca unos de otros, y la suya es una historia de violencia tan antigua como ambas razas. En general, los enanos desconfían de los semiorcos y los evitan. Creen que los medianos, los elfos y los gnomos son demasiado frágiles, cambiantes o ‘monines’ para ser dignos de un respeto adecuado. Con los humanos es con quienes los enanos conectan mejor, puesto que la naturaleza industriosa y los recios apetitos de estos son los que más se aproximan al ideal enano',
	'alignment-dwaf'		=>	'A los enanos les guían el honor y la tradición y, aunque se les satiriza a menudo como orgullosos, tienen un fuerte sentido de la amistad y de la justicia, y quienes se ganan su confianza saben que, si bien trabajan duro, también saben disfrutar a lo grande, en especial si hay cerveza de por medio. La mayoría de los enanos son legales buenos, y prefieren adorar a dioses cuyos preceptos encajen en esos rasgos, siendo Torag uno de sus favoritos, aunque Abadar y Gorum también son elecciones comunes.',
	'adventure-dwaf'		=>	'Aunque los aventureros enanos son raros comparados con los humanos, se les puede encontrar en la mayoría de regiones del mundo. Los enanos abandonan a menudo los confines de sus reductos en busca de gloria para su clan, riquezas con las que enriquecer la fortaleza-hogar donde nacieron, o para recuperar ciudadelas enanas caídas, ahora en manos de sus enemigos raciales. El arte de la guerra enano se caracteriza a menudo por las tácticas de combate en túneles, y por la lucha cuerpo a cuerpo; es por ello por lo que la mayoría de enanos tienden hacia clases como la de guerrero y la de bárbaro.',
	'racial-dwaf'			=>	'<u>+2 a Constitución, +2 a Sabiduría, -2 a Carisma</u>: los enanos son a la vez duros y sabios, pero también un poco broncos.
	<br><u>Mediano</u>: los enanos son criaturas Medianas, y no tienen bonificador ni penalizador debido al tamaño.
	<br><u>Lento y calmado</u>: los enanos tienen una velocidad base de 20 pies (6 m), que nunca se ve modificada por la armadura ni la impedimenta.
	<br><u>Visión en la oscuridad</u>: los enanos pueden ver en la oscuridad hasta 60 pies (18 m).
	<br><u>Entrenamiento defensivo</u>: los enanos tienen un bonificador +4 de esquiva a la CA contra monstruos del subtipo gigante.
	<br><u>Avaricia</u>: los enanos obtienen un bonificador +2 racial a las pruebas de Tasación hechas para determinar el precio de los objetos no mágicos, que contengan metales preciosos o piedras preciosas.
	<br><u>Odio</u>: los enanos tienen un bonificador +1 a las tiradas de ataque contra criaturas humanoides de los subtipos orco y goblin, debido a un entrenamiento especial contra dichos enemigos odiados.
	<br><u>Resistente</u>: los enanos obtienen un bonificador +2 racial a las tiradas de salvación contra veneno, conjuros, y aptitudes sortílegas.
	<br><u>Estabilidad</u>: los enanos obtienen un bonificador +4 racial a su Defensa contra maniobras de combate, cuando resisten a una embestida o intento de derribo estando de pie.
	<br><u>Afinidad con la piedra</u>: los enanos obtienen un bonificador +2 a las pruebas de Percepción para darse cuenta de trabajos en piedra poco usuales, como trampas y puertas ocultas situadas en muros o suelos de piedra. Tienen derecho a una prueba para darse cuenta de tales rasgos siempre que pasan a 10 pies (3 m) o menos de alguno de ellos, tanto si están buscando activamente como si no. Familiaridad con las armas: los enanos son competentes con hachas de batalla, picos pesados, y martillos de guerra, y tratan cualquier arma con la palabra ‘enano’ en su nombre como un arma marcial.
	<br><u>Idiomas</u>: los enanos empiezan el juego hablando enano y común. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger de entre los siguientes: gigante, gnomo, goblin, infracomún, orco, y térraro.',

	//Gnomes
	'name-gnome'			=>	'Gnomos',
	'desc-gnome'			=>	'Los gnomos remontan su linaje hasta el misterioso reino de las hadas, un lugar donde los colores son más brillantes, las tierras salvajes son aún más salvajes, y las emociones son más primitivas. Fuerzas desconocidas empujaron a los antiguos gnomos hasta sacarles de dicho reino, obligándoles a buscar refugio en este mundo; a pesar de ello, ni abandonaron del todo sus raíces feéricas, ni se adaptaron a la cultura mortal. Como resultado, las otras razas ven a los gnomos como ajenos y extraños.',
	'desc-physical-gnome'	=>	'Los gnomos son una de las más pequeñas de las razas comunes, y generalmente miden poco más de 3 pies (90 cm) de altura. Su cabello tiende hacia colores vibrantes como el anaranjado intenso de las hojas de otoño, el verde frondoso de los bosques en primavera, o los rojos oscuros y púrpuras de las flores salvajes en plena floración. Similarmente, sus tonos de piel van de los marrones terrosos a los rosas florales, frecuentemente poco relacionados con la genética. Los gnomos poseen características faciales altamente variables, y muchos poseen bocas y ojos bastante grandes, un efecto que puede ser a la vez inquietante y asombroso, dependiendo del individuo.',
	'society-gnome'			=>	'A diferencia de la mayoría de las razas, los gnomos no suelen organizarse a lo largo de estructuras societarias clásicas. Son criaturas profundamente caprichosas, que típicamente viajan solas o con acompañantes temporales, y que siempre buscan experiencias nuevas y más excitantes. Raramente forman relaciones duraderas entre sí o con miembros de las otras razas, emprendiendo en vez de ello oficios, profesiones, o colecciones con una pasión que bordea el exceso de celo. Los gnomos varones tienen una extraña afición por los sombreros y cubrecabezas poco usuales, mientras que las mujeres suelen llevar a menudo peinados elaborados y excéntricos.',
	'relation-gnome'		=>	'Los gnomos tienen dificultades para relacionarse con las demás razas, tanto física como emocionalmente. Su humor es difícil de interpretar, y a menudo parece maligno o carente de sentido para el resto de las razas, mientras que a su vez ellos tienden a pensar que las razas mayores son gigantes torpes y aburridos. Se llevan bien con los medianos y los humanos, pero les encanta sobremanera burlarse de los enanos y de los semiorcos, a quienes la mayoría de gnomos cree que necesitan que les alegren. Respetan a los elfos, pero a menudo se frustran con el ritmo comparativamente lento con el que los miembros de la raza más longeva toman sus decisiones. Para los gnomos, la acción siempre es mejor que la inacción, y muchos de ellos llevan consigo en todo momento diversos proyectos de elevada complejidad, para mantenerse entretenidos durante los períodos de descanso.',
	'alignment-gnome'		=>	'Aunque los gnomos son bromistas impulsivos, con motivos a veces inescrutables y métodos igualmente confusos, su corazón se suele encontrar en el lugar correcto. Son dados a poderosos impulsos y emociones, y se suelen encontrar en paz con el mundo natural. Los gnomos suelen ser neutrales buenos, prefiriendo adorar a dioses que valoren la individualidad y la Naturaleza, como Shelyn, Gozreh, Desna, y cada vez más Cayden Cailean',
	'adventure-gnome'		=>	'La propensión de los gnomos al ansia viajera les convierte en aventureros natos. A menudo se hacen vagabundos para experimentar nuevos aspectos de la vida, puesto que no hay nada más novedoso que los incontables peligros a los que se enfrentan los aventureros. Los gnomos compensan su debilidad física con una afición por la hechicería o por la interpretación de los bardos',
	'racial-gnome'			=>	'<u>+2 a Constitución, +2 a Carisma, -2 a Fuerza</u>: los gnomos son físicamente débiles, pero sorprendentemente resistentes, y su actitud les hace naturalmente agradables.
	<br><u>Pequeño</u>: los gnomos son criaturas Pequeñas, que obtienen por ello un bonificador +1 por tamaño a su CA, un bonificador +1 por tamaño a sus tiradas de ataque, un penalizador -1 a su Bonificador de maniobras de combate y a su Defensa contra maniobras de combate, y un bonificador +4 por tamaño a las pruebas de Sigilo.
	<br><u>Velocidad lenta</u>: los gnomos tienen una velocidad base de 20 pies (6 m).
	<br><u>Visión en la penumbra</u>: los gnomos pueden ver el doble que los humanos en condiciones de luz tenue.
	<br><u>Entrenamiento defensivo</u>: los gnomos obtienen un bonificador +4 de esquiva a la CA contra los monstruos del subtipo gigante.
	<br><u>Magia de los gnomos</u>: los gnomos suman +1 a la CD de cualquier tirada de salvación contra los conjuros de ilusión que lanzan. Los que tienen Carisma 11 o más, también obtienen las siguientes aptitudes sortílegas: 1/día – luces danzantes, sonido fantasma, prestidigitación, y hablar con los animales. El nivel de lanzador para estos efectos es igual al nivel del gnomo. La CD para estos conjuros es igual a 10 + el nivel del conjuro + su modificador de Carisma.
	<br><u>Odio</u>: los gnomos obtienen un bonificador +1 a las tiradas de ataque contra las criaturas humanoides de los subtipos reptiliano y goblin ,debido a un entrenamiento especial contra esos enemigos odiados.
	<br><u>Resistencia a la ilusión</u>: los gnomos obtienen un bonificador +2 racial a las tiradas de salvación contra los conjuros y los efectos de ilusión.
	<br><u>Sentidos agudos</u>: los gnomos obtienen un bonificador +2 racial a las pruebas de Percepción.
	<br><u>Obsesivo</u>: los gnomos obtienen un bonificador +2 racial a una habilidad de Artesanía o Profesión de su elección.
	<br><u>Familiaridad con las armas</u>: los gnomos tratan cualquier arma con la palabra ‘gnomo’ en su nombre como marcial.
	<br><u>Idiomas</u>: los gnomos empiezan el juego hablando común, gnomo, y silvano. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger entre los siguientes: dracónico, elfo, enano, gigante, goblin, y orco.',

	//Humans
	'name-human'			=>	'Humanos',
	'desc-human'			=>	'Los humanos poseen un empuje excepcional, y una gran capacidad para resistir y expandirse, y como tales son actualmente la raza dominante del mundo. Sus imperios y naciones son vastos y en creciente aumento, y los ciudadanos de dichas sociedades esculpen nombres para sí con la fuerza de la espada y el poder de los conjuros. La humanidad se caracteriza por ser tumultuosa y diversa, y las culturas humanas van desde las tribus salvajes pero honorables, hasta las familias nobles decadentes y adoradoras del diablo en las ciudades más cosmopolitas. La curiosidad y la ambición humanas a menudo triunfan sobre su predilección por un estilo de vida sedentario, y muchos abandonan sus hogares para explorar los innumerables rincones olvidados del mundo, o dirigir poderosos ejércitos para conquistar a sus vecinos, simplemente porque pueden.',
	'desc-physical-human'	=>	'Las características físicas de los humanos son tan variadas como los climas del mundo. Desde los miembros de las tribus de los continentes meridionales, de piel oscura, hasta los asaltantes bárbaros y de piel pálida de las tierras septentrionales, los humanos poseen una enorme variedad de tonos de piel, tipos de cuerpo, y rasgos faciales. En general, el color de piel de los humanos se hace más oscuro conforme más cerca del ecuador viven.',
	'society-human'			=>	'Las sociedades humanas comprenden una multitud de gobiernos, actitudes, y estilos de vida. Aunque las culturas humanas más antiguas remontan su historia a miles de años en el pasado, comparadas con las sociedades de razas comunes como los elfos y los enanos, las sociedades humanas parecen hallarse en un estado de constante flujo, con imperios que se fragmentan, y nuevos reinos reemplazando a los viejos. Por lo general, a los humanos se les conoce por su flexibilidad, su ingenio, y su ambición.',
	'relation-human'		=>	'Los humanos son fértiles, y su empuje y sus números a menudo les espolean a entrar en contacto con otras razas durante brotes de expansión territorial y de colonización. En muchos casos, eso conduce a la violencia y a la guerra, pero los humanos también son rápidos en perdonar y en forjar alianzas con razas que no intentan compararse con ellos o excederles en violencia. Orgullosos a veces hasta el punto de la arrogancia, los humanos podrían ver a los enanos como borrachos miserables, a los elfos como esnobs cambiantes, a los medianos como ladrones cobardes, a los gnomos como maníacos retorcidos, y a los semielfos y semiorcos como razas embarazosas, pero la diversidad de la raza entre sus propios miembros también hace a los humanos bastante adeptos a aceptar a los demás tal y como son.',
	'alignment-human'		=>	'La humanidad es quizá la más heterogénea de todas las razas comunes, con una capacidad tremenda tanto para grandes males como para el bien sin límites. Algunos se reúnen en vastas hordas bárbaras, mientras que otros construyen ciudades extensas que cubren varias millas. En su conjunto, la mayoría de humanos son neutrales, y sin embargo tienden a congregarse en naciones y civilizaciones con alineamientos específicos. Los humanos también tienen la más amplia gama de dioses y de religiones, careciendo de los ligámenes de otras razas con la tradición, y listos para volverse hacia cualquiera que les ofrezca gloria o protección. Incluso han adoptado dioses como Torag o Calistria, quienes durante milenios estuvieron más identificados con razas más antiguas, y conforme la humanidad continúa creciendo y prosperando, nuevos dioses han empezado a emerger de sus leyendas en continua expansión.',
	'adventure-human'		=>	'La ambición por sí sola empuja a incontables humanos, y para muchos las aventuras son un medio para obtener un fin, ya sea la riqueza, la aclamación, el estatus social, o el saber arcano. Unos cuantos persiguen carreras de aventureros simplemente por la excitación del peligro. Los humanos proceden de miles de regiones y de trasfondos, y por ello pueden ocupar cualquier rol en un grupo aventurero',
	'racial-human'			=>	'<u>+2 a una puntuación de característica</u>: los personajes humanos obtienen un bonificador +2 a una puntuación de característica de su elección a la creación del personaje, para representar su variada naturaleza.
	<br><u>Mediano</u>: los humanos son criaturas Medianas, y no tienen bonificador ni penalizador debido al tamaño.
	<br><u>Velocidad normal</u>: los humanos tienen una velocidad base de 30 pies (9 m).
	<br><u>Dote adicional</u>: los humanos seleccionan una dote adicional a 1er nivel.
	<br><u>Hábil</u>: los humanos obtienen un rango de habilidad adicional a 1er nivel, y otro rango adicional cada vez que suben de nivel.
	<br><u>Idiomas</u>: los humanos empiezan el juego hablando común. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger cualquier idioma que quieran (excepto idiomas secretos como el druídico).',

	//Mediums
	'name-medium'			=>	'Medianos',
	'desc-medium'			=>	'Optimistas y alegres por naturaleza, bendecidos con una suerte enorme, y empujados por una poderosa ansia viajera, los medianos compensan su corta estatura con una gran abundancia de valor y de curiosidad. A la vez excitables y de trato fácil, a los medianos les gusta mantener la calma y tener la vista puesta en la oportunidad, y no son tan dados como algunas de las razas más volátiles a estallidos violentos o emocionales. Incluso en las fauces de la catástrofe, un mediano casi nunca pierde el sentido del humor.
	<br>Los medianos son oportunistas inveterados. Incapaces de defenderse físicamente de los rigores del mundo, saben cuándo plegarse con el viento, y cuándo esconderse. Y sin embargo, la curiosidad de un mediano a menudo supera su sentido común, lo que le lleva a decisiones poco meditadas, y a escapatorias por los pelos.
	<br>Aunque su curiosidad les empuja a viajar y buscar nuevos lugares y experiencias, los medianos poseen un fuerte sentido de la casa y el hogar, y a menudo gastan por encima de sus medios para aumentar las comodidades de la vida hogareña.',
	'desc-physical-medium'	=>	'Los medianos alcanzan como máximo la humilde altura de 3 pies (90 cm). Prefieren ir descalzos, lo que lleva a que las plantas de sus pies sean callosas. Matas de cabello grueso y rizado caldean la parte superior de sus pies anchos y bronceados. Su piel tiende hacia un color almendra, y su cabello hacia tonos claros de marrón. Las orejas de un mediano son puntiagudas, pero proporcionalmente no mucho más grandes que las de un humano.',
	'society-medium'		=>	'los medianos no reclaman ninguna tierra como origen de su cultura, ni controlan asentamientos mayores que asambleas rurales de pueblos libres. Con mayor frecuencia, habitan a las rodillas de sus primos humanos en ciudades humanas, ganándose la vida como pueden, de las migajas de las sociedades más grandes. Muchos medianos llevan una vida perfectamente fructífera a la sombra de sus vecinos mayores, mientras que otros prefieren vidas más nómadas en el camino, viajando por el mundo y experimentando todo lo que éste tiene que ofrecerles.',
	'relation-medium'		=>	'Un mediano típico se enorgullece de su capacidad para pasar desapercibido a las demás razas, y es precisamente este rasgo el que permite a tantos medianos alcanzar la excelencia en los trucos y en el latrocinio. Por ello, la mayoría de medianos, sabiendo bien la visión estereotipada que otras razas tienen de ellos, se toman muchos molestias en ser amistosos y abiertos con las razas mayores cuando no intentan pasar desapercibidos. Se llevan bastante bien con los gnomos, aunque la mayoría de los medianos contemplan a estas excéntricas criaturas con una buena dosis de cautela. Los medianos coexisten bien con los humanos por regla general, pero como quiera que algunas de las sociedades humanas más agresivas valoran a los medianos como esclavos, estos intentan no mostrarse demasiado complacientes cuando tienen tratos con ellas. Los medianos respetan a los elfos y a los enanos, pero estas razas suelen vivir en regiones remotas, lejos de las comodidades de la civilización de las que los medianos disfrutan, lo que limita las oportunidades de interaccionar. Sólo los semiorcos son generalmente evitados por los medianos, puesto que su gran tamaño y su violenta naturaleza son demasiado intimidatorios para la mayoría de ellos.',
	'alignment-medium'		=>	'Los medianos son leales a sus amigos y a su familia, pero como viven en un mundo dominado por razas el doble de altas que ellos, han llegado a acostumbrarse a que a veces es necesario rebuscar entre las sobras o depender de la caridad para sobrevivir. Como resultado, la mayoría de medianos son neutrales. Los medianos favorecen a dioses que animan a las comunidades pequeñas y fuertemente entrelazadas, ya sea para bien (como Erastil), o para mal (como Norgorber).',
	'adventure-medium'		=>	'Su inherente buena suerte, aunada a su insaciable ansia viajera, hace que los medianos sean ideales para la vida del aventurero. Otros vagabundos de parecido carácter tienden a unirse a la curiosa raza, en espera de que parte de su mística suerte se les pegue.',
	'racial-medium'			=>	'<u>+2 a Destreza, +2 a Carisma, -2 a Fuerza</u>: los medianos son ágiles y de voluntad fuerte, pero su reducida talla hace que sean más débiles que otras razas.
	<br><u>Pequeño</u>: los medianos son criaturas Pequeñas, que obtienen por ello un bonificador +1 por tamaño a su CA, un bonificador +1 por tamaño a sus tiradas de ataque, un penalizador -1 a su Bonificador de maniobras de combate y a su Defensa contra las maniobras de combate, y un bonificador +4 por tamaño a las pruebas de Sigilo.
	<br><u>Velocidad lenta</u>: los medianos tienen una velocidad base de 20 pies (6 m).
	<br><u>Sin miedo</u>: los medianos obtienen un bonificador +2 racial a todas las tiradas de salvación contra miedo, que se apila con el concedido por la suerte del mediano.
	<br><u>Suerte del mediano</u>: los medianos obtienen un bonificador +1 racial a todas las tiradas de salvación.
	<br><u>Sentidos agudos</u>: los mediano obtienen un bonificador +2 racial a las pruebas de Percepción.
	<br><u>Pies firmes</u>: los medianos obtienen un bonificador +2 racial a las pruebas de Acrobacias y de Trepar.
	<br><u>Familiaridad con las armas</u>: los medianos son competentes con las hondas, y tratan cualquier arma con la palabra ‘mediano’ en el nombre como un arma marcial.
	<br><u>Idiomas</u>: los medianos empiezan el juego hablando común y mediano. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger entre los siguientes: elfo, enano, gnomo, y goblin.',

	//Semielfs
	'name-semielf'			=>	'Semielfos',
	'desc-semielf'			=>	'Los elfos han atraído desde siempre los ojos codiciosos de las demás razas. Su generoso ciclo vital, su afinidad por la magia, y su gracia inherente, contribuyen a la admiración o a la envidia más amarga de sus vecinos. Sin embargo, de todos sus rasgos, el que más atrae a sus asociados humanos es el de la belleza. Desde que ambas razas entraron en contacto por vez primera, los humanos han tenido a los elfos como un modelo de perfección física, viendo en el Pueblo gentil versiones idealizadas de sí mismos. Por su parte, muchos elfos encuentran atractivos a los humanos a pesar de sus costumbres comparativamente bárbaras, atraídos por la pasión y el ímpetu con el que los miembros de la raza más joven viven sus cortas vidas.
	<br>A veces, esta atracción mutua conduce a relaciones románticas. Aunque por lo general de corta duración, incluso para los estándares humanos, estos escarceos suelen llevar al nacimiento de semielfos, una raza derivada de dos culturas, pero heredera de ninguna. Los semielfos pueden procrear entre sí, pero incluso estos semielfos de ‘sangre pura’ tienden a ser considerados como bastardos, tanto por los humanos como por los elfos.',
	'desc-physical-semielf'	=>	'Los semielfos son más altos que los humanos pero menos que los elfos. Heredan la complexión delgada y los rasgos agraciados de su linaje élfico, pero el color de su piel viene dictado por su lado humano. Si bien retienen las orejas puntiagudas de los elfos, las suyas son mas redondeadas y menos pronunciadas. Los ojos de un semielfo, que se parecen a los de los humanos, tienden a un espectro de colores exóticos, que van desde el ámbar o el violeta hasta el verde esmeralda y el azul oscuro.',
	'society-semielf'	=>	'La falta de un país y de una cultura unificados obligan a los semielfos a ser versátiles, y capaces de adaptarse a casi cualquier entorno. Si bien a menudo son atractivos para ambas razas por las mismas razones que sus padres, los semielfos raramente encajan con los humanos ni con los elfos, puesto que cada raza ve en ellos demasiadas pruebas de la otra. Esta falta de aceptación pesa mucho sobre la mayoría de semielfos, y sin embargo hay otros que se ven reforzados por su estatus único, teniendo su falta de una cultura formalizada como lo último en libertad. Como resultado, los semielfos son increíblemente adaptables, y capaces de ajustar sus talentos y sus esquemas mentales a cualesquiera sociedades en las que se encuentren.',
	'relation-semielf'		=>	'Un semielfo entiende la soledad, y sabe que el carácter a menudo es menos producto de la raza que de la experiencia vital. Por ello, los semielfos están a menudo abiertos a amistades y alianzas con otras razas, y son menos dados a confiar en las primeras impresiones cuando se forman una opinión sobre gente a la que acaban de conocer.',
	'alignment-semielf'		=>	'El aislamiento de los semielfos influencia fuertemente sus caracteres y filosofías. La crueldad no les es natural, ni lo es mezclarse con la sociedad o doblegarse a sus convenciones; como resultado, la mayoría de los semielfos son caóticos buenos. La falta de una cultura unificada por parte de los semielfos hace menos probable que se vuelvan hacia la religión, pero quienes lo hacen suelen seguir las creencias comunes de su tierra natal.',
	'adventure-semielf'		=>	'Los semielfos tienden a ser itinerantes, vagabundeando por la tierra en busca de un lugar al que poder llamar finalmente hogar. El deseo de probarse a sí mismos ante la comunidad, y de establecer una identidad personal o incluso un legado, conducen a muchos aventureros semielfos a vidas valerosas.',
	'racial-semielf'		=>	'<u>+2 a una puntuación de característica</u>: los personajes semielfos obtienen un bonificador +2 a una puntuación de característica de su elección a la creación del personaje para representar su variada naturaleza.
	<br><u>Mediano</u>: los semielfos son criaturas Medianas, y no tienen bonificador ni penalizador debido al tamaño.
	<br><u>Velocidad normal</u>: los semielfos tienen una velocidad base de 30 pies (9 m).
	<br><u>Visión en la penumbra</u>: los semielfos pueden ver el doble que los humanos en condiciones de luz tenue.
	<br><u>Adaptabilidad</u>: los semielfos obtienen Soltura con una habilidad como dote adicional a 1er nivel.
	<br><u>Sangre élfica</u>: los semielfos cuentan a la vez como humanos y como elfos para cualquier efecto relacionado con la raza.
	<br><u>Inmunidades élficas</u>: los semielfos son inmunes a los efectos del sueño mágico, y obtienen un bonificador +2 racial a las tiradas de salvación contra los conjuros y efectos de hechizar.
	<br><u>Sentidos agudos</u>: los semielfos obtienen un bonificador +2 racial a las pruebas de Percepción.
	<br><u>Multitalento</u>: los semielfos escogen dos clases favoritas a 1er nivel y obtienen +1 punto de golpe o +1 punto de habilidad cada vez que suben un nivel en cualquiera de dichas clases. Consulta el Capítulo 3 para más información sobre las clases favoritas.
	<br><u>Idiomas</u>: los semielfos empiezan el juego hablando común y elfo. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger cualquier idioma que deseen (excepto idiomas secretos como el druídico).',

	//Semiorcs
	'name-orc'			=>	'Semiorcos',
	'desc-orc'			=>	'Los semiorcos son monstruosidades, cuyo trágico nacimiento es el resultado de la perversión y la violencia, o por lo menos así es como las demás razas les ven. Es cierto que los semiorcos raramente son el resultado de uniones en las que el amor está de por medio, y como resultado se suelen ver obligados a crecer de forma rápida y dura, luchando constantemente en busca de protección, o para hacerse un nombre por sí mismos. Temidos, motivo de desconfianza, y objeto de desprecio, los semiorcos consiguen sorprender de forma consistente a sus detractores con grandes gestas y una sabiduría inesperada, aunque a veces es más fácil aporrear cabezas.',
	'desc-physical-orc'	=>	'Ambos géneros de semiorco miden entre 6 y 7 pies de altura (entre 1,80 y 2,10 m) con complexiones recias, y piel verdosa o grisácea. Los caninos a menudo les crecen lo suficiente como para sobresalirles de la boca, y éstos ‘colmillos’, combinados con un entrecejo pronunciado y unas orejas ligeramente puntiagudas, les proporcionan una apariencia notoriamente bestial. Si bien los semiorcos pueden ser impresionantes, pocos les describen como agraciados.',
	'society-orc'		=>	'A diferencia de los semielfos, en los que por lo menos parte de la discriminación social surge de los celos o de la atracción, los semiorcos se llevan lo peor de ambos mundos: físicamente más débiles que sus congéneres orcos, tienden a ser temidos o directamente atacados por las legiones de humanos que no se preocupan por la diferencia que hay entre los orcos auténticos y los mestizos. Sin embargo, y aunque no sean estrictamente aceptados, los semiorcos de las sociedades civilizadas tienden a ser valorados por su capacidad marcial, y se sabe que los líderes orcos han procurado propagarlos de forma intencional, puesto que los mestizos saben compensar de forma regular su falta de fuerza física con una astucia y una agresividad incrementadas, lo que les convierte en caudillos naturales y consejeros estratégicos.',
	'relation-orc'		=>	'Toda una vida de persecución convierte al semiorco típico en precavido y rápido en irritarse, y sin embargo quienes atraviesan su salvaje exterior podrían encontrar un núcleo de empatía bien escondido. Los elfos y los enanos tienden a ser los que menos aceptan a los semiorcos, viendo en ellos un parecido demasiado grande con sus enemigos raciales, pero las otras razas tampoco son mucho más comprensivas. Las sociedades humanas que tienen pocos problemas con los orcos tienden a ser las más acomodaticias, y allí los semiorcos trabajan de forma natural como mercenarios y como matones.',
	'alignment-orc'		=>	'Obligados a vivir, o bien entre los brutales orcos, o bien como exiliados solitarios en las tierras civilizadas, la mayoría de los semiorcos son amargos, violentos, y reclusivos. El mal les llega con facilidad, pero no son malignos por naturaleza sino que la mayoría son caóticos neutrales, habiendo aprendido por experiencia que no hay razón alguna para hacer nada sino lo que les beneficia de forma directa. Cuando se molestan en adorar a los dioses, intentan favorecer a dioses que promueven la guerra o la fuerza individual, como Gorum, Cayden Cailean, Lamashtu y Rovagug',
	'adventure-orc'		=>	'Fuertemente independientes, muchos semiorcos adoptan la vida del aventurero por necesidad, buscando escapar de su doloroso pasado, o mejorar su posición gracias a la fuerza de las armas. Otros, más optimistas o desesperados por la aceptación, adoptan el manto del cruzado para demostrar su valor al mundo',
	'racial-orc'		=>	'<u>+2 a una puntuación de característica</u>: los personajes semiorcos obtienen un bonificador +2 a una puntuación de característica de su elección a la creación del personaje, para representar su variada naturaleza.
	<br><u>Mediano</u>: los semiorcos son criaturas Medianas, y no tienen bonificador ni penalizador debido al tamaño.
	<br><u>Velocidad normal</u>: los semiorcos tienen una velocidad base de 30 pies (9 m).
	<br><u>Visión en la oscuridad</u>: los semiorcos pueden ver en la oscuridad hasta 60 pies (18 m).
	<br><u>Intimidante</u>: los semiorcos obtienen un bonificador +2 racial a sus pruebas de Intimidar debido a su terrible naturaleza.
	<br><u>Sangre orca</u>: los semiorcos cuentan a la vez como humanos y como orcos para cualquier efecto relacionado con la raza.
	<br><u>Ferocidad orca</u>: 1 vez al día, si un semiorco queda reducido a menos de 0 puntos de golpe pero no resulta muerto, puede luchar durante 1 asalto más como si estuviera incapacitado. Al final de su siguiente turno, a menos que se le lleve por encima de los 0 puntos de golpe, queda inconsciente de inmediato y empieza a morir.
	<br><u>Familiaridad con las armas</u>: los semiorcos son competentes con las grandes hachas y los alfanjes, y tratan cualquier arma con la palabra ‘orco’ en su nombre como un arma marcial.
	<br><u>Idiomas</u>: los semiorcos empiezan el juego hablando común y orco. Los que tienen puntuaciones de Inteligencia elevadas pueden escoger entre los siguientes: abisal, dracónico, gigante, gnoll, y goblin.',

	//General
	'title-desc-physical'	=>	'Descripción física',
	'title-society'			=>	'Sociedad',
	'title-relations'		=>	'Relaciones',
	'title-alignment'		=>	'Alineamiento y religión',
	'title-adventure'		=>	'Aventureros',
	'title-racial'			=>	'Rasgos raciales',
];
?>